### ISSUE TITLE
Help Installing ftwrunner

### ISSUE THREAD

**Issue by GNU-Plus-Windows-User** [digitalwave/ftwrunner#1]
Hi, I'm trying to install ftwrunner and when I run ``./configure`` I get an error saying this package is missing ``libyaml-cpp``, I've installed this package ``sudo apt install libyaml-cpp-dev`` but I'm not sure if that's the correct package.

**Comment by GNU-Plus-Windows-User** [comment]
@airween

**Comment by airween** [comment]
> Hi, I'm trying to install ftwrunner and when I run `./configure` I get an error saying this package is missing `libyaml-cpp`, I've installed this package `sudo apt install libyaml-cpp-dev` but I'm not sure if that's the correct package.

This is the correct package - could you show the output of this command?

```
dpkg -l "libyaml-cpp-dev"
```

**Comment by GNU-Plus-Windows-User** [comment]
@airween 
```
Desired=Unknown/Install/Remove/Purge/Hold
| Status=Not/Inst/Conf-files/Unpacked/halF-conf/Half-inst/trig-aWait/Trig-pend
|/ Err?=(none)/Reinst-required (Status,Err: uppercase=bad)
||/ Name            Version            Architecture Description
+++-===============-==================-============-===================================================
ii  libyaml-cpp-dev 0.7.0+dfsg-8build1 amd64        YAML parser and emitter for C++ - development files
```

**Comment by airween** [comment]
On which Linux distribution and version do you try to install?

**Comment by GNU-Plus-Windows-User** [comment]
@airween Ubuntu 22.04 LXC Container for Proxmox

**Comment by airween** [comment]
Hmm... it's very weird.

I've tried now and I get:

```
$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 22.04.1 LTS
Release:	22.04
Codename:	jammy

$ ./configure 
checking for g++... g++
checking whether the C++ compiler works... yes
checking for C++ compiler default output file name... a.out
checking for suffix of executables... 
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C++ compiler... yes
checking whether g++ accepts -g... yes
checking for gcc... gcc
checking whether we are using the GNU C compiler... yes
checking whether gcc accepts -g... yes
checking for gcc option to accept ISO C89... none needed
checking whether gcc understands -c and -o together... yes
checking how to run the C preprocessor... gcc -E
checking for grep that handles long lines and -e... /usr/bin/grep
checking for egrep... /usr/bin/grep -E
checking for ANSI C header files... yes
checking for sys/types.h... yes
checking for sys/stat.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for memory.h... yes
checking for strings.h... yes
checking for inttypes.h... yes
checking for stdint.h... yes
checking for unistd.h... yes
checking modsecurity/modsecurity.h usability... yes
checking modsecurity/modsecurity.h presence... yes
checking for modsecurity/modsecurity.h... yes
checking pcre.h usability... yes
checking pcre.h presence... yes
checking for pcre.h... yes
checking for msc_init in -lmodsecurity... yes
checking for pcre_compile in -lpcre... yes
configure: error: libyaml-cpp is not installed.

$ sudo apt install libyaml-cpp-dev
...
$ ./configure 
checking for g++... g++
checking whether the C++ compiler works... yes
checking for C++ compiler default output file name... a.out
checking for suffix of executables... 
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C++ compiler... yes
checking whether g++ accepts -g... yes
checking for gcc... gcc
checking whether we are using the GNU C compiler... yes
checking whether gcc accepts -g... yes
checking for gcc option to accept ISO C89... none needed
checking whether gcc understands -c and -o together... yes
checking how to run the C preprocessor... gcc -E
checking for grep that handles long lines and -e... /usr/bin/grep
checking for egrep... /usr/bin/grep -E
checking for ANSI C header files... yes
checking for sys/types.h... yes
checking for sys/stat.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for memory.h... yes
checking for strings.h... yes
checking for inttypes.h... yes
checking for stdint.h... yes
checking for unistd.h... yes
checking modsecurity/modsecurity.h usability... yes
checking modsecurity/modsecurity.h presence... yes
checking for modsecurity/modsecurity.h... yes
checking pcre.h usability... yes
checking pcre.h presence... yes
checking for pcre.h... yes
checking for msc_init in -lmodsecurity... yes
checking for pcre_compile in -lpcre... yes
checking for stdbool.h that conforms to C99... no
checking for _Bool... no
checking for size_t... yes
checking for ssize_t... yes
checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
checking for a thread-safe mkdir -p... /usr/bin/mkdir -p
checking for gawk... gawk
checking whether make sets $(MAKE)... yes
checking whether make supports the include directive... yes (GNU style)
checking whether make supports nested variables... yes
checking dependency style of gcc... gcc3
checking dependency style of g++... gcc3
checking that generated files are newer than configure... done
configure: creating ./config.status
config.status: creating Makefile
config.status: creating src/Makefile
config.status: creating config.h
config.status: config.h is unchanged
config.status: executing depfiles commands

$ make
...

$ src/ftwrunner -h
This is ftwrunner
Avaliable arguments:
 -h This help
 -c Use alternative config instead of ftwrunner.yaml in same directory
 -m Use alternative ModSecurity config instead of in default config
 -f Use alternative ftw test collection instead of in default config
 -r Use only this ruleset, eg. '-r 911100'
 -t Use only this test of all, eg. '-t 1'
 -d Debug mode - in case of FAILED test the error log lines showed
```

Do you have the necessary files?

```bash
$ ls -la /usr/include/yaml-cpp/yaml.h /usr/lib/x86_64-linux-gnu/libyaml-cpp.a
-rw-r--r-- 1 root root    795 Jul 10  2021 /usr/include/yaml-cpp/yaml.h
-rw-r--r-- 1 root root 946570 Mar 25  2022 /usr/lib/x86_64-linux-gnu/libyaml-cpp.a
```

You should try to run `make clean`, `autoreconf --install` and `./configure` again.

**Comment by GNU-Plus-Windows-User** [comment]
@airween Yes those files exist
```
-rw-r--r-- 1 root root    795 Jul 11  2021 /usr/include/yaml-cpp/yaml.h
-rw-r--r-- 1 root root 946570 Mar 25  2022 /usr/lib/x86_64-linux-gnu/libyaml-cpp.a
```

There is no make file so ``make clean`` doesn't work

**Comment by airween** [comment]
> There is no make file so `make clean` doesn't work

And the others?

**Comment by GNU-Plus-Windows-User** [comment]
@airween these are the other files that exist
```
AUTHORS  COPYING  Makefile.am  NEWS    README.md  aclocal.m4  autom4te.cache  config.h     config.h.in~  configure     configure~  ftwrunner.yaml.example  stamp-h1
CHANGES  INSTALL  Makefile.in  README  TODO.txt   autogen.sh  build-aux       config.h.in  config.log    configure.ac  depcomp     src
```

**Comment by airween** [comment]
I mean what about the other commands? Eg. `autoreconf --install` and then `./configure`.

**Comment by GNU-Plus-Windows-User** [comment]
@airween ``autoreconf --install`` works but there is no output, ``./configure`` has the same problem as mentioned earlier
```
checking for g++... g++
checking whether the C++ compiler works... yes
checking for C++ compiler default output file name... a.out
checking for suffix of executables...
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether the compiler supports GNU C++... yes
checking whether g++ accepts -g... yes
checking for g++ option to enable C++11 features... none needed
checking for gcc... gcc
checking whether the compiler supports GNU C... yes
checking whether gcc accepts -g... yes
checking for gcc option to enable C11 features... none needed
checking whether gcc understands -c and -o together... yes
checking for stdio.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for inttypes.h... yes
checking for stdint.h... yes
checking for strings.h... yes
checking for sys/stat.h... yes
checking for sys/types.h... yes
checking for unistd.h... yes
checking for modsecurity/modsecurity.h... yes
checking for pcre.h... yes
checking for msc_init in -lmodsecurity... yes
checking for pcre_compile in -lpcre... yes
configure: error: libyaml-cpp is not installed.
```

**Comment by airween** [comment]
Could you send me the `configure.log` file in private?

**Comment by GNU-Plus-Windows-User** [comment]
@airween sure, but I don't see any way to send DMs on github.

**Comment by airween** [comment]
Check my profile by clicking on my username beside the comment box - you can see my address.

**Comment by GNU-Plus-Windows-User** [comment]
@airween I emailed you the log file

**Comment by airween** [comment]
Thanks, I got it - looks like it's not a `yaml` problem but the `libmodsecurity3` issue. (This is because of the `configure` script is wrong I guess - I'll check that soon).

So how is your libmodsecurity3 package?

**Comment by GNU-Plus-Windows-User** [comment]
@airween I'm still using the one I compiled myself, the repository you linked (In ModSecurity issues) has outdated versions and doesn't support the latest security fixes with CRS. The package I currently have installed still has segfaults.

**Comment by airween** [comment]
> I'm still using the one I compiled myself, the repository you linked (In ModSecurity issues) has outdated versions and doesn't support the latest security fixes with CRS.

Which ModSecurity issues are you thinking about? ModSecurity and CRS are two different entities.

If you have a custom built library, I assume you installed it under /usr/local/, right? Could you check that?
```
find /usr/local -name "modsecurity.h"
find /usr/local -name "libmodsecurity3.so"
```
Then you have to set up the path's through CFLAGS, like
```
export CFLAGS="-I/usr/local/include -L/usr/local/lib" && ./configure
```

**Comment by GNU-Plus-Windows-User** [comment]
@airween Yes I'm aware ModSecurity and CRS are 2 different entities, I'm referring to this https://coreruleset.org/20220919/crs-version-3-3-3-and-3-2-2-covering-several-cves/, the repository you shared only goes up to 3.0.6, 3.0.8 is required according to the linked article.

Yes it's installed under ``/usr/local/modsecurity/`` which is the default location I believe.

I still get the same output when using ``export CFLAGS="-I/usr/local/modsecurity/include -L/usr/local/modsecurity/lib" && ./configure``.

**Comment by airween** [comment]
> the repository you shared only goes up to 3.0.6, 3.0.8 is required according to the linked article.

No, definitely not :smiley:.

As you [can see](https://modsecurity.digitalwave.hu/ubuntu/pool/main/m/modsecurity/), it provides [3.0.9-pre](https://modsecurity.digitalwave.hu/ubuntu/pool/main/m/modsecurity/libmodsecurity-dev_3.0.9~pre-20220910-ubuntu0-22.04.1_amd64.deb), that's a September state. Ubuntu packages have built from same source as [Debian packages](https://modsecurity.digitalwave.hu/debian/pool/main/m/modsecurity/), the naming convention is a bit different, but in case of Debian you can see the commit hash: `996c7e1` which points to the ModSecurity release [v3.0.8](https://github.com/SpiderLabs/ModSecurity/commit/996c7e1e1f782111331e0ff37cbaf6c6a29c3530). So, this repository actually contains v3.0.8.

> Yes it's installed under /usr/local/modsecurity/ which is the default location I believe.

Right.

> I still get the same output when using `export CFLAGS="-I/usr/local/modsecurity/include -L/usr/local/modsecurity/lib" && ./configure`

Could you show me your output of the two `find` commands above?

**Comment by GNU-Plus-Windows-User** [comment]
@airween Ok I'll give those packages a try then and see if it fixes my issue

Regarding the find command
```
$ find /usr/local -name "modsecurity.h"
/usr/local/modsecurity/include/modsecurity/modsecurity.h
$ find /usr/local -name "libmodsecurity3.so"
```
There is no output for the second command

**Comment by airween** [comment]
> There is no output for the second command

Sorry, it was my mistake - you should try
```
find /usr/local -name "libmodsecurity.so*"
```

**Comment by GNU-Plus-Windows-User** [comment]
```
/usr/local/modsecurity/lib/libmodsecurity.so.3.0.8
/usr/local/modsecurity/lib/libmodsecurity.so.3
/usr/local/modsecurity/lib/libmodsecurity.so.3.0.7
/usr/local/modsecurity/lib/libmodsecurity.so
```

**Comment by airween** [comment]
Ah, sorry, you have to set up both `CFLAGS` **AND** `CXXFLAGS` too. So, the correct command is this:

```
export CFLAGS="-I/usr/local/modsecurity/include -L/usr/local/modsecurity/lib/" && export CXXFLAGS="-I/usr/local/modsecurity/include -L/usr/local/modsecurity/lib/" && ./configure
```

(In the config.log it seems that the problem is with the `g++`, not with the `gcc` - sorry, I didn't realize it previously.)

**Comment by airween** [comment]
>  the repository you shared only goes up to 3.0.6, 3.0.8 is required according to the linked article.

Just one last note about versions - please take a look to the main page of the repository:

https://modsecurity.digitalwave.hu/

There is a version matrix, where you can see the provided versions from each packages. Note that CRS also have a patched version (3.3.4) from September.

**Comment by GNU-Plus-Windows-User** [comment]
@airween That did it! Thank you for your help, I'll start running some tests and see if it can find my problem.

**Comment by GNU-Plus-Windows-User** [comment]
@airween I was going to run some tests today, but now it's saying ``./ftwrunner: error while loading shared libraries: libmodsecurity.so.3: cannot open shared object file: No such file or directory`` when I run ``./ftwrunner``, I've already configured the ``ftwrunner.yaml`` file.

**Comment by airween** [comment]
`cannot open shared object file` occurs when the loader does not find the necessary shared library.

In this case, you should add the path to the environment variable `LD_LIBRARY_PATH`:

```
$ src/ftwrunner -h
src/ftwrunner: error while loading shared libraries: libmodsecurity.so.3: cannot open shared object file: No such file or directory

$ export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/local/modsecurity/lib

$ src/ftwrunner -h
This is ftwrunner
Avaliable arguments:
 -h This help
 -c Use alternative config instead of ftwrunner.yaml in same directory
 -m Use alternative ModSecurity config instead of in default config
 -f Use alternative ftw test collection instead of in default config
 -r Use only this ruleset, eg. '-r 911100'
 -t Use only this test of all, eg. '-t 1'
 -d Debug mode - in case of FAILED test the error log lines showed

```

**Comment by GNU-Plus-Windows-User** [comment]
@airween that did it.
I've ran the test and almost everything has failed, I assume I haven't done anything wrong?
```
SUMMARY:
===============================
PASSED:                   198
FAILED:                   2165
FAILED (whitelisted):     3
SKIPPED:                  30
===============================
TOTAL:                    2396
===============================
```

**Comment by airween** [comment]
First: it's a good news that your library (libmodsecurity3) works as well, there is no segfault (as you explained in your first issue under ModSecurity repository). This tool proves this.

While are there so many failed tests - to answer this, I need to see your config file and the whole command line with other arguments.

**Comment by GNU-Plus-Windows-User** [comment]
I just ran the command ``./ftwrunner`` with no other arguments passed to it
the yaml file is configured as
```
modsecurity_config: /etc/nginx/waf-rules/coreruleset/modsecurity.conf
ftwtest_root: /etc/nginx/waf-rules/coreruleset/
test_whitelist:
- 941190-3 # known MSC bug - PR #2023 (Cookie without value)
- 941330-1 # know MSC bug - #2148 (double escape)
- 942480-2 # known MSC bug - PR #2023 (Cookie without value)
- 944100-11 # known MSC bug - PR #2045, ISSUE #2146
- 944100-12
- 944100-15
- 944100-16
- 944110-11 # known MSC bug - PR #2045, ISSUE #2146
- 944110-12
- 944110-15
- 944110-16
```

**Comment by airween** [comment]
`modsecurity_config: /etc/nginx/waf-rules/coreruleset/modsecurity.conf` - it's "just" the regular modsecurity.conf. Where does the engine loads the rules? Perhaps you have to make a local file which includes both `modsecurity.conf` and CRS load files, like:
```
include /etc/nginx/waf-rules/coreruleset/modsecurity.conf
include /etc/nginx/waf-rules/coreruleset/owasp-crs.load
```
and pass this file to `modsecurity_config`. Of course, if you load the rules in `modsecurity.conf`, you shouldn't do this.

`ftwtest_root: /etc/nginx/waf-rules/coreruleset/` - is this the root path of the tests? I assume this directory contains the whole CRS structure - here is mine:
```
ftwtest_root: /home/airween/modsecurity-crs-3.3.4/tests/regression/tests
```
Then you will still get many failed tests, but not as much as before.

**Comment by GNU-Plus-Windows-User** [comment]
@airween I use this server as a reverse proxy and have multiple vhost file
under ``/etc/nginx/waf-rules/`` I will have multiple conf files for various virtual hosts for example ``wordpress-rules.conf`` will load the CRS along with exclusion rules and any other custom rules I've written for wordpress. then within ``/etc/nginx/sites-enabled/`` I will include the path to ``/etc/nginx/waf-rules/wordpress-rules.conf`` for the wordpress vhost.

``/etc/nginx/waf-rules/coreruleset/`` is CRS, the ``modsecurity.conf`` file is also placed here, all custom rules I've written including exclusion rules are under ``/etc/nginx/waf-rules/customruleset/``

**Comment by airween** [comment]
I see your points, may be that solution works in case of Nginx (if Nginx loads the rules with directive `modsecurity_rules_file`.

But `ftwrunner` needs a config where the engine loads the rules explicitly.

Please also note, that there are many rules in CRS which activated only on higher PL ([Paranoia level](https://coreruleset.org/docs/concepts/paranoia_levels/)). If a rule does not active (because you run CRS on PL1), then its test will failed.

Here is my test result on PL4 on Ubuntu 2204:
```
SUMMARY:
===============================
PASSED:                   2327
FAILED:                   30
FAILED (whitelisted):     9
SKIPPED:                  30
===============================
TOTAL:                    2396
===============================
FAILED TESTS:             944210-5, 944210-6, 944210-22, 944210-23, 944210-39, 944210-40, 944120-5, 944120-6, 944120-22, 944120-23, 944120-39, 944120-40, 944120-56, 944120-57, 944120-73, 944120-74, 944120-90, 944120-91, 944120-107, 944120-108, 944120-124, 944120-125, 920460-1, 920460-2, 920460-3, 920460-4, 920181-1, 922100-1, 922120-1, 922110-1
===============================
PASSED WHITELISTED TESTS: 942480-2, 941190-3
```

I think the failed tests are there because some incompatibility issue in libmodsecurity3.

**Comment by GNU-Plus-Windows-User** [comment]
@airween I changed modsecurity_config to ``modsecurity_config: /etc/nginx/waf-rules/nextcloud-rules.conf`` and reran tests

Nextcloud at PL-2
```
SUMMARY:
===============================
PASSED:                   1543
FAILED:                   817
FAILED (whitelisted):     6
SKIPPED:                  30
===============================
TOTAL:                    2396
===============================
```
Nextcloud at PL-4
```
SUMMARY:
===============================
PASSED:                   1923
FAILED:                   437
FAILED (whitelisted):     6
SKIPPED:                  30
===============================
TOTAL:                    2396
===============================
```

**Comment by airween** [comment]
Could you send me the whole `/etc/nginx/waf-rules/nextcloud-rules.conf` in private?

**Comment by GNU-Plus-Windows-User** [comment]
@airween I've emailed you the file

**Comment by airween** [comment]
Thanks, I received it.

Unfortunately I'm afraid I can't help you in this case.

The rule set is a bit more complex (generally CRS is a complex rule set), you have some more additions and exceptions, therefore the base test case line is not "compatible" with your rules. I mean it is possible that a test case is failed because some exception disables the activation... 18% would be a bit high value, but not in this special case.

It clearly seems that as you increased the PL, the number of failed tests decreased, so the tool works as it expected.

Feel free to ask if you have any question, but I think you've reached the maximum value what you could with this tool.

**Comment by GNU-Plus-Windows-User** [comment]
@airween I don't know if this is any use but I've disabled all custom rules, it's just pure CRS at PL-4 and got this result
```
SUMMARY:
===============================
PASSED:                   2325
FAILED:                   32
FAILED (whitelisted):     9
SKIPPED:                  30
===============================
TOTAL:                    2396
===============================
```


But nethertheless Thank You for everything you've done to help, I'll give that repository you suggested a try.

**Comment by airween** [comment]
Yes, 32 is definitely a good value.

It's good to see that works :).

I'm going to close this issue.
